#    _  ___        ______       ____
#   / |/ (_)_ __  / __/ /  ___ / / /
#  /    / /\ \ / _\ \/ _ \/ -_) / /
# /_/|_/_//_\_\ /___/_//_/\__/_/_/
# ----------------------------------
# Shell nix home packages by lPhiNix
#
{
  pkgs,
  config,
  lib,
  ...
}: let
  inherit (lib) concatStringsSep mapAttrsToList;
  fishSet = n: v: "set -gx ${n} \"${v}\"";
in {
  home.packages = with pkgs; [
    fish # Shell (command interpreter)

    starship # Shell prompt
    fastfetch # System fetch

    figlet # ASCII text generator
    cava # Audio visualizer

    cmatrix # Matrix digital rain
    tty-clock # Terminal clock
    cbonsai # Growing bonsai tree
    pipes # Pipes terminal screensaver
    hollywood # Fake 'hacker' console activity
  ];

  # Fish does not source /etc/profile, so Home Manager's hm-session-vars.sh is
  # never read. Translate home.sessionVariables/sessionPath into a conf.d
  # snippet fish picks up, without managing config.fish (owned by dotfiles).
  xdg.configFile."fish/conf.d/hm-session-vars.fish".text = ''
    # Generated by Home Manager: expose home.sessionVariables/sessionPath to fish.
    ${concatStringsSep "\n" (mapAttrsToList fishSet config.home.sessionVariables)}
    ${concatStringsSep "\n" (map (p: "fish_add_path \"${p}\"") config.home.sessionPath)}
  '';
}
